// Generates ui/src/bravura-font.ts from the Bravura woff2 that ships inside
// @coderline/alphatab, so the webview can render SMuFL glyphs fully offline.
// Re-run after bumping @coderline/alphatab. Output is committed.
import { readFileSync, writeFileSync, readdirSync, lstatSync, existsSync } from "node:fs";
import { join } from "node:path";

function findFile(dir, predicate) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = lstatSync(full); // lstat: don't follow symlinks, so a symlink cycle can't loop
    if (st.isDirectory()) {
      const hit = findFile(full, predicate);
      if (hit) return hit;
    } else if (predicate(entry)) {
      return full;
    }
  }
  return null;
}

const root = "node_modules/@coderline/alphatab";
if (!existsSync(root)) {
  console.error(`\n  embed-font: ${root} not found — run \`npm install\` first.\n`);
  process.exit(1);
}
const woff2 = findFile(root, (f) => /^Bravura.*\.woff2$/i.test(f));
if (!woff2) {
  console.error("\n  embed-font: could not find Bravura*.woff2 under " + root + ".\n");
  process.exit(1);
}

const b64 = readFileSync(woff2).toString("base64");
const out = `// AUTO-GENERATED by scripts/embed-font.mjs from ${woff2}.
// Bravura (SMuFL) as a data URI so AlphaTab renders glyphs offline. Do not edit by hand.
export const BRAVURA_WOFF2_DATAURI = "data:font/woff2;base64,${b64}";
`;
writeFileSync("ui/src/bravura-font.ts", out);
console.log(`  embed-font: wrote ui/src/bravura-font.ts from ${woff2} (${(b64.length / 1024).toFixed(0)} KB base64)`);
